= RVI repos manifest

RVI has many link:https://lf-riscv.atlassian.net/wiki/spaces/HOME/pages/16154706/GitHub+Repo+Map[github org's] with many repositories that represent the work being done.  There are tools that make it easier to work with multiple repos.  This proof of concept (POC) provides one example.

== Details

This will show how to do the following tasks across the "dev" and "user" roles:

* dev
** use github CLI tool `gh` and `jq` to generate a manifest (XML listing of multiple repos)
* user
** use link:https://gerrit.googlesource.com/git-repo/[git `repo` tool] to work with the repos in that manifest

NOTE: `repo` has many features that won't be covered in here or even needed (like `upload`ing changeset to gerrit server)

=== Prerequisites

* dev
** install and configure (authorize) link:https://cli.github.com/[`gh`]
** install link:https://jqlang.github.io/jq/[`jq`]
* user
** Install link:https://gerrit.googlesource.com/git-repo/#install[git `repo` tool]

=== Using manifest files

===== Initialize repos with `repo init`

Similarly to cloning a single repo, the first step in using `repo` is to link:https://source.android.com/docs/setup/reference/repo#init[initialize] a directory with the configuration (manifest file).  This should be done in an empty dir.

There currently is only one `default.xml` manifest file that has been created.  It contains all the projects of all the orgs that RVI uses.  To filter down by organization or projects, use the `--groups=` feature of the `repo init` command.

Here's an example:
[source, bash]
----
mkdir rvi-repos && cd rvi-repos
repo init -u https://github.com/riscv-admin/docs-sig --groups=all,-org:riscv-android-src
----

NOTE: If a `--manifest` isn't provided, `default.xml` is assumed

NOTE: `--groups=all` is a special group to check out all

NOTE: If a `-` is used in front of a group, negates its use

==== Clone/pull repos content with `repo sync`

After `repo init` is done once, `repo sync` can be used to clone the initial repos and keep them sync'ed with their remotes in the future.

NOTE: All `git` commands will continue to work in the individual projects as expected.

==== Cherry-pick edits across multiple repos (or how to use `repo foreach` to do work across multiple repos)

The goal of the example is to cherry-pick a commit from another repo and apply it to other repos using link:https://source.android.com/docs/setup/reference/repo#forall[`repo forall`]

NOTE: This example only shows doing it for one repo but the changes could be more broadly applied.

* create a dev branch:
** `repo start dev/kbroch/dependabot-update-docs-resources-submodule riscv/riscv-isa-manual`
* add remote that contains commit you want to cherry-pick:
** `repo forall riscv/riscv-isa-manual -v -c 'echo $REPO_PROJECT; git remote add docs-spec-template git@github.com:riscv/docs-spec-template.git'`
* fetch the remote above:
** `repo forall riscv/riscv-isa-manual -v -c 'echo $REPO_PROJECT; git fetch docs-spec-template'`
* cherry-pick the commit wanted:
** `repo forall riscv/riscv-isa-manual -v -c 'echo $REPO_PROJECT; git cherry-pick 5c19f62e25aeeda69886b07e7ec2959b1e632735'`
* push changes:
** `repo forall riscv/riscv-isa-manual -v -c 'echo $REPO_PROJECT; git push origin HEAD'`

NOTE: At this point, PRs need to be created individually.

=== Dev tasks

==== Generating a manifest file

Although manifest files can be created manually, a bash script is used here to do it automatically.

Simple run `make`

.Example output:
[source,shell]
----
❯ make
./generate-manifests.sh generated/default.xml riscv riscv-admin riscv-android-src riscv-collab riscv-non-isa riscv-software-src
Fetching repositories for organization: riscv
Fetching repositories for organization: riscv-admin
Fetching repositories for organization: riscv-android-src
Fetching repositories for organization: riscv-collab
Fetching repositories for organization: riscv-non-isa
Fetching repositories for organization: riscv-software-src
XML manifest generated: generated/default.xml
----

=== Pros and cons

* Pros
** perform git commands on multiple repos at the same time
* Cons
** generated manifests are currently generated manually so changes to all the RVI repos won't be picked up automatically
*** deletions especially will generate a `repo rsync` failure for that given repo (but not fatal for the tool)

== References

List of multi-repo tools:

* https://gerrit.googlesource.com/git-repo/
* https://manicli.com/
* https://github.com/nosarthur/gita
* https://github.com/fabioz/mu-repo
* https://github.com/asottile/all-repos
